# Generated by Django 5.2 on 2025-04-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_service', '0003_alter_transaction_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
